from aiogram.types import ReplyKeyboardMarkup, KeyboardButton, ReplyKeyboardRemove
bt_contact = KeyboardButton('Поделиться номером телефона 📞', request_contact=True)
bt_one = KeyboardButton('Поиск 🔍')
bt_plus = KeyboardButton('🔼')
bt_minus = KeyboardButton('🔽')
bt_all_spaces = KeyboardButton('Посмотреть свободные места ✅')
bt_authorize = KeyboardButton('Авторизация')
tel_num = ReplyKeyboardMarkup(resize_keyboard=True)
search = ReplyKeyboardMarkup(resize_keyboard=True)
authorize = ReplyKeyboardMarkup(resize_keyboard=True)
spaces = ReplyKeyboardMarkup(resize_keyboard=True)
search.add(bt_one).add(bt_plus, bt_minus).add(bt_all_spaces)
tel_num.add(bt_contact)
authorize.add(bt_authorize)
