version: "3.7"
services:
  parking_postgres:
    image: dpage/pgadmin4
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: info@uzavtosanoat.uz
        PGADMIN_DEFAULT_PASSWORD: sanCtfAXeZP95HcZ
    ports:
      - "8001:80"
    depends_on:
      - parking_db
  parking_db:
    image: postgres
    volumes:
      - parking_db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=uzauto_parking_db
      - POSTGRES_USER=uzauto_parking_user
      - POSTGRES_PASSWORD=LIATYnJc3gy49ybm
  parking_web:
    build: .
    command: python tgAdmin/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=uzauto_parking_db
      - POSTGRES_USER=uzauto_parking_user
      - POSTGRES_PASSWORD=LIATYnJc3gy49ybm
    depends_on:
      - parking_db
volumes:
  parking_db_volume:
