# Generated by Django 4.0.3 on 2022-03-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0003_alter_employees_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='block_comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Причина Блокировки'),
        ),
        migrations.AddField(
            model_name='security',
            name='blocked',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='color',
            field=models.TextField(verbose_name='Цвет Автомобиля'),
        ),
    ]
