# Generated by Django 4.0.3 on 2022-03-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0004_security_block_comment_security_blocked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpaces',
            fields=[
                ('busy_spaces', models.IntegerField(default=0, verbose_name='Занято мест')),
                ('all_spaces', models.IntegerField(default=100, verbose_name='Все места')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
    ]
